# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todolist.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etodolist.proto\x12\x08todolist\"6\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"=\n\x0cTodoResponse\x12\x1c\n\x04todo\x18\x01 \x01(\x0b\x32\x0e.todolist.Todo\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x10TodoListResponse\x12\x1d\n\x05todos\x18\x01 \x03(\x0b\x32\x0e.todolist.Todo\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xb9\x01\n\x08TodoList\x12\x31\n\x07\x41\x64\x64Todo\x12\x0e.todolist.Todo\x1a\x16.todolist.TodoResponse\x12\x37\n\x08GetTodos\x12\x0f.todolist.Empty\x1a\x1a.todolist.TodoListResponse\x12\x41\n\nDeleteTodo\x12\x1b.todolist.DeleteTodoRequest\x1a\x16.todolist.TodoResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todolist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_TODO']._serialized_start=28
  _globals['_TODO']._serialized_end=82
  _globals['_TODORESPONSE']._serialized_start=84
  _globals['_TODORESPONSE']._serialized_end=145
  _globals['_TODOLISTRESPONSE']._serialized_start=147
  _globals['_TODOLISTRESPONSE']._serialized_end=196
  _globals['_DELETETODOREQUEST']._serialized_start=198
  _globals['_DELETETODOREQUEST']._serialized_end=229
  _globals['_EMPTY']._serialized_start=231
  _globals['_EMPTY']._serialized_end=238
  _globals['_TODOLIST']._serialized_start=241
  _globals['_TODOLIST']._serialized_end=426
# @@protoc_insertion_point(module_scope)
